applications:
  apps:
    - appName: gea-firewall
      project: default
      appImage: gm-firewall
      destCluster: k8s-tools
      destNamespace: production
      ingressHost: cf-whitelist-updater.geadev.com
      autoscaling:
        enabled: true
      healthcheck:
        liveness: /ha.php
        readiness: /ha.php
      slack: devops-deploy

    - appName: gea-render
      project: portal
      appImage: gm-render
      chartName: gea-render
      destCluster: k8s-render
      destNamespace: development
      ingressHost: cdn-geaflare.geadev.com
      valuesCustom: values.render
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: crm-render

    - appName: gea-render
      project: portal
      appImage: gm-render
      destCluster: k8s-render
      destNamespace: production
      ingressHost: cdn.geaflare.com
      valuesCustom: values.render
      resources:
        limits:
          cpu: 2360m
          memory: 4096Mi
        requests:
          cpu: 2048m
          memory: 4096Mi
      autoscaling:
        enabled: true
        min: 5
        max: 15
        cpu: 75
        memory: 75
      slack: crm-render

    - appName: gea-oms
      project: erp
      appImage: gm-oms-devtest
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: dev-account.geadev.com
      ingressHost2: dev-crm.geadev.com
      # healthcheck:
      #   liveness: /healthcheck/liveness
      #   readiness: /healthcheck/readiness
      revisionHistoryLimit: 3
      resources:
        limits:
          cpu: 1280m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: devops-oms

    - appName: gea-oms-sandbox
      project: erp
      appImage: gm-oms-sandbox
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: sandbox.geadev.com
      revisionHistoryLimit: 3
      resources:
        limits:
          cpu: 1280m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: devops-oms

    - appName: gea-gmprint
      project: erp
      appImage: gmp-print
      chartName: gea-gmprint
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: gmprint.geadev.com
      servicePort: 3000
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: odoo-tech

    - appName: gea-gmprint-api
      project: erp
      appImage: gmp-print-api
      chartName: gea-gmprint-api
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: gmprint-api.geadev.com
      servicePort: 8000
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: odoo-tech

    - appName: app-web
      project: portal
      appImage: app-fe
      chartName: app-web
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: app.geadev.com
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: appv2

    - appName: app-api
      project: portal
      appImage: app-be
      chartName: app-api
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: app-api.geadev.com
      healthcheck:
        liveness: /seller/healthz
        readiness: /seller/readiness
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: appv2
      
    - appName: app-web
      project: portal
      appImage: app-fe
      chartName: app-web
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: app.gearment.com
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: appv2

    - appName: app-api
      project: portal
      appImage: app-be
      chartName: app-api
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: app-prod-api.geadev.com
      healthcheck:
        liveness: /seller/healthz
        readiness: /seller/readiness
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      volumeName: av2-uploads
      volumeClaimName: av2-uploads0
      volumePath: /home/fff/www/uploads
      slack: appv2

    - appName: oms-crm
      project: oms
      appImage: gm-oms-crm
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: crm.gearment.com
      revisionHistoryLimit: 3
      healthcheck:
        liveness: /healthcheck/liveness
        readiness: /healthcheck/readiness
      resources:
        limits:
          cpu: 1536m
          memory: 3072Mi
        requests:
          cpu: 1280m
          memory: 3072Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      volumeName: crm-uploads
      volumeClaimName: crm-uploads0
      volumePath: /home/fff/www/uploads
      slack: devops-oms

    - appName: oms-api
      project: oms
      appImage: gm-oms-crm
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: crm-api.gmone.net
      revisionHistoryLimit: 3
      healthcheck:
        liveness: /healthcheck/liveness
        readiness: /healthcheck/readiness
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: devops-oms

    - appName: gm-worker
      project: oms
      appImage: gm-worker
      chartName: gm-worker
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: report.geadev.com
      ingressHost2: report-webhook.geadev.com
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
#      slack: crm-reports
      teams: https://gearmentinc.webhook.office.com/webhookb2/1476b39f-9d9f-4d83-9851-ce7ac115ee3c@92ab7646-e7fe-4eb7-a29b-436d706c0a3d/IncomingWebhook/8311c5fc4997482699df869e01e131d7/f62080b2-0210-4a9c-ad65-b737537be39a

    - appName: gm-worker
      project: oms
      appImage: gm-worker
      chartName: gm-worker
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: report.gearment.com
      ingressHost2: report-webhook-prod.geadev.com
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
      slack: crm-reports

    - appName: account-web
      project: oms
      appImage: gm-oms-account
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: account.gearment.com
      revisionHistoryLimit: 3
      healthcheck:
        liveness: /healthcheck/liveness
        readiness: /healthcheck/readiness
      resources:
        limits:
          cpu: 1536m
          memory: 3072Mi
        requests:
          cpu: 1280m
          memory: 3072Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: devops-oms

    - appName: account-api
      project: oms
      appImage: gm-oms-account
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: account.gearment.com
      ingressPath: /api/v2
      revisionHistoryLimit: 3
      healthcheck:
        liveness: /healthcheck/liveness
        readiness: /healthcheck/readiness
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: devops-oms

    - appName: oms-cron
      project: oms
      appImage: gm-oms-cron
      destCluster: k8s-crm
      destNamespace: production
      ingressHost: prod-cron.geadev.com
      ingressPath: /
      revisionHistoryLimit: 3
      healthcheck:
        liveness: /healthcheck/liveness
        readiness: /healthcheck/readiness
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
        memory: 75
      slack: devops-oms

    # - project: erp
    #   appName: gea-oms
    #   appImage: gm-oms
    #   destCluster: k8s-crm
    #   destNamespace: production
    #   ingressHost: crm2.gearment.com
    #   revisionHistoryLimit: 3
    #   resources:
    #     limits:
    #       cpu: 1536m
    #       memory: 3072Mi
    #     requests:
    #       cpu: 1280m
    #       memory: 3072Mi
    #   autoscaling:
    #     enabled: true
    #     min: 1
    #     max: 3
    #     cpu: 75
    #     memory: 75

    # - appName: template
    #   #project: default
    #   appImage: gm-firewall
    #   destCluster: k8s-tools
    #   destNamespace: production
    #   ingressHost: cf-whitelist-updater.geadev.com
    #   ingressPath: /
    #   valuesCustom: development
    #   revisionHistoryLimit: 5
    #   resources:
    #     limits:
    #       cpu: 768m
    #       memory: 512Mi
    #     requests:
    #       cpu: 512m
    #       memory: 512Mi
    #   autoscaling:
    #     enabled: true
    #     min: 1
    #     max: 3
    #     cpu: 75
    #     memory: 75
      # healthcheck:
      #   liveness: /
      #   readiness: /
      # slack: devops-deploy
