applications:
  apps:
    - appName: gm-worker
      project: oms
      appImage: gm-worker
      chartName: gm-worker
      destCluster: k8s-crm
      destNamespace: development
      ingressHost: report.geadev.com
      ingressHost2: report-webhook.geadev.com
      resources:
        limits:
          cpu: 1270m
          memory: 2048Mi
        requests:
          cpu: 1024m
          memory: 2048Mi
      autoscaling:
        enabled: true
        min: 1
        max: 3
        cpu: 75
      teams: https://gearmentinc.webhook.office.com/webhookb2/1476b39f-9d9f-4d83-9851-ce7ac115ee3c@92ab7646-e7fe-4eb7-a29b-436d706c0a3d/IncomingWebhook/8311c5fc4997482699df869e01e131d7/f62080b2-0210-4a9c-ad65-b737537be39a