apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry-1.docker.io
      credentials: secret:argocd/docker-creds#creds
      defaultns: library
      credsexpire: 5h55m
      default: false
    - name: My ECR Registry
      prefix: 282660418429.dkr.ecr.ap-southeast-1.amazonaws.com
      api_url: https://282660418429.dkr.ecr.ap-southeast-1.amazonaws.com
      credentials: secret:argocd/aws-ecr-creds#creds
      credsexpire: 5h55m
      default: true
