apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret-updater
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-updater
  namespace: argocd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-updater
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-secret-updater
subjects:
  - kind: ServiceAccount
    name: ecr-secret-updater
