apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-cronjob
  namespace: argocd
spec:
  project: default
  destination:
    name: k8s-tools
  source:
    repoURL: https://github.com/lyhuuloi/helm-gea.git
    targetRevision: HEAD
    path: image-updater
  syncPolicy:
    automated:
      selfHeal: true
      #prune: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
