apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog-filebeat-tools
  namespace: argocd
spec:
  project: default
  destination:
    name: k8s-tools
  source:
    repoURL: https://github.com/kankun92/test-noti.git
    targetRevision: HEAD
    path: logging
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
