apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: portal
  namespace: argocd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: erp
  namespace: argocd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
